name: Biweekly Release

on:
  # Run on the 1st and 15th of every month (approx. every 2 weeks)
  schedule:
    - cron: '0 0 1,15 * *'
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: seriaati/create-release@main
        with:
          python_version: "3.9"
          tool: "uv"
          update: "true"