name: Create Release

on:
  push:
    branches:
      - master
    paths:
      - pyproject.toml
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Create release
        uses: seriaati/create-release@main
        with:
          pypi_token: ${{ secrets.PYPI_API_TOKEN }}
          tool: "uv"
